version: '3'
services:
  backup-manager:
    image: mmmaxwwwell/backup-manager
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    container_name: backup-manager
    restart: always
    volumes:
      - ./local_backup:/home/node/app/local_backup
      - ./backup_source:/home/node/app/backup_source
      - ./storage:/home/node/app/storage
    env_file:
      - ./secrets/.env